alias code="open -a Visual\ Studio\ Code"
alias coffee="caffeinate"
alias d="docker"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias finder="open `pwd`"
alias f="fuck"
alias ff="fzf"
alias gcne="git commit -a --amend --no-edit"
alias gp="git push"
alias gpf="git push -f"
alias hg="history | grep"
alias k="kubectl"
alias k19="kubectl19"
alias kgc="kubectl config get-contexts"
alias ll="ls -al"
alias lz="lazygit"
alias n="nvim"
alias nz="nvim ~/.zshrc"
alias nzz="nvim ~/.config/zshrc/"
alias oa="okta-aws"
alias p3="python3"
#alias pip="pip3"
#alias python="python3"
alias p="podman"
alias pcu="podman-compose up -d"
alias pcd="podman-compose down"
alias pcr="podman-compose down; podman-compose up -d"
alias sz="source ~/.zshrc"
alias shad="ssh-add ~/.ssh/twgbitbucket"
alias t="tmux"
alias ta="tmux attach"
alias xx="exit"
alias :q="exit"

b64() {
 echo $1 | base64 -d
}

